namespace BypassEmote.Localization;

/// <summary> 中文文案：<c>UI/DebugWindow.cs</c>。 </summary>
internal static class ZhDebugWindow
{
    internal static readonly (string En, string Zh)[] Entries =
    [
        ("Bypass Emote Debug", "Bypass Emote 调试"),
        ("IPC Tests", "IPC 测试"),
        ("Tracked Characters", "追踪的角色"),
        ("Network Relay", "网络中继"),
        ("Swap Layers", "替换层"),
        ("Emote Pool", "情感动作池"),
        ("Kept Swaps", "保留的替换"),
        ("Patch Approval", "补丁审批"),
        ("The gate is not up.", "审批闸门尚未就绪。"),
        ("Probed client: {0}", "探测到的客户端：{0}"),
        ("Gate reads: {0}", "闸门读取到：{0}"),
        ("Pretend this is the Korean client", "假装这是韩服客户端"),
        ("Pretend this is the Chinese client", "假装这是国服客户端"),
        ("Pretend this client cannot be identified", "假装无法识别此客户端"),
        ("Pretend Penumbra rejects the player identifier (KR/CN clients debug)", "假装 Penumbra 拒绝玩家标识（韩服/国服客户端调试用）"),
        ("Client is Global. Enable one of the client checkboxes above.", "当前为国际服客户端。请勾选上方任一客户端选项。"),
        ("Fallback in use: {0}", "正在使用回退方案：{0}"),
        ("Assignment chain:", "分配链："),
        ("Game build: {0}", "游戏版本：{0}"),
        ("Status: {0}", "状态：{0}"),
        ("Reason: {0}", "原因：{0}"),
        ("Notice: {0}", "通知：{0}"),
        ("Governs: {0}    Holds hooks: {1}    Held: {2}", "接管：{0}    持有 Hook：{1}    已持有：{2}"),
        ("as soon as the loop runs", "循环运行后立即"),
        ("Next automatic check: {0}", "下次自动检查：{0}"),
        ("Drop the recorded approval", "清除已记录的审批"),
        ("Clears the approval stored in the config and at runtime", "清除配置中和运行时保存的审批"),
        ("Notice for this build", "本次构建的说明"),
        ("Approve this build in the .json file", "在 .json 文件中批准本次构建"),
        ("The swap mod manager is not initialized.", "替换模组管理器尚未初始化。"),
        ("Mod directory: {0}", "模组目录：{0}"),
        ("<no character loaded>", "（未加载角色）"),
        ("Penumbra: {0}", "Penumbra：{0}"),
        ("Drawn body: {0}", "绘制骨架：{0}"),
        ("<unknown>", "（未知）"),
        ("Swap files: {0}", "替换文件：{0}"),
        ("Clear kept swaps", "清除保留的替换"),
        ("No swap is kept.", "没有保留的替换。"),
        ("Target", "目标"),
        ("Source", "来源"),
        ("Option", "选项"),
        ("Races", "种族"),
        ("Last used", "最近使用"),
        ("Selected", "已选中"),
        ("Rules", "规则"),
        ("(idle pose)", "（待机动作）"),
        ("yes", "是"),
        ("no", "否"),
        ("Select", "选中"),
        ("Turn off", "取消选中"),
        ("does not hold the mod", "未持有该模组"),
        ("{0}, priority {1}", "{0}，优先级 {1}"),
        ("enabled", "已启用"),
        ("disabled", "已禁用"),
        ("Network relay is not initialized.", "网络中继尚未初始化。"),
        ("Network: {0}", "网络：{0}"),
        ("State: {0}", "状态：{0}"),
        ("(hub)", "（主机）"),
        ("Self: {0}", "自身：{0}"),
        ("Active", "启用"),
        ("LAN discovery", "局域网发现"),
        ("Instances on the same PC find each other with no configuration.\nLAN discovery reaches other PCs, and may need a Windows Firewall inbound allow.", "同一台电脑上的多个实例无需配置即可互相发现。\n局域网发现可连接到其他电脑，可能需要放行 Windows 防火墙的入站规则。"),
        ("Peers:", "节点："),
        ("You - {0} [{1}]", "你 - {0} [{1}]"),
        ("hub", "主机"),
        ("client", "客户端"),
        ("same PC", "同一台电脑"),
        ("LAN", "局域网"),
        ("Swap owned emotes", "替换已拥有的情感动作"),
        ("Sends emotes you already own through the swap instead of letting the game play them, for debugging only.", "让你已拥有的情感动作也走替换流程，而不是由游戏直接播放，仅供调试。"),
        ("Weapon in hand", "手持武器"),
        ("Weapon stow at end", "结束时收起武器"),
        ("Weapon travel animation", "武器移动动画"),
        ("IPC Version: {0}", "IPC 版本：{0}"),
        ("IPC Is Ready: {0}", "IPC 就绪：{0}"),
        ("Select Emote:", "选择情感动作："),
        ("None", "无"),
        ("Search emotes...", "搜索情感动作..."),
        ("Set local player state", "设置本地玩家状态"),
        ("Set target state", "设置目标状态"),
        ("Clear local player state", "清除本地玩家状态"),
        ("Clear target state", "清除目标状态"),
        ("Current Local Player IPC Data (Looping only):", "当前本地玩家 IPC 数据（仅循环情感动作）："),
        ("Current Target IPC Data (Looping only):", "当前目标 IPC 数据（仅循环情感动作）："),
        ("Tracked Characters:", "追踪的角色："),
        ("Serialization error: {0}", "序列化错误：{0}"),
        ("Unknown ({0})", "未知（{0}）"),
    ];
}