namespace BypassEmote.Localization;

/// <summary> 中文文案：<c>UI/EmotePoolTab.cs</c>。 </summary>
internal static class ZhEmotePoolTab
{
    internal static readonly (string En, string Zh)[] Entries =
    [
        ("The emote catalog is still building.", "情感动作目录仍在构建中。"),
        ("Search emotes...", "搜索情感动作..."),
        ("State", "状态"),
        ("Read my state", "读取我的状态"),
        ("Refresh", "刷新"),
        ("Refused", "已拒绝"),
        ("Kept out", "已排除"),
        ("rules: loop {0}, turn {1}, sound {2}, modded {3}, idle pose {4}, dispatch {5}", "规则：循环 {0}，转身 {1}，音效 {2}，模组 {3}，待机动作 {4}，派发 {5}"),
        ("off", "关闭"),
        ("{0}, {1} per rank, {2}", "{0}，每档 {1} 个，{2}"),
        ("(not here)", "（此处不可用）"),
        ("No source emote selected.", "尚未选择来源情感动作。"),
        ("Emote Swap is not running, so there is nothing to preview.", "表情替换未运行，没有可预览的内容。"),
        ("Nothing to show.", "没有可显示的内容。"),
        ("Filter targets...", "筛选目标情感动作..."),
        (", you pressed {0}", "，你按下的是 {0}"),
        ("Pose family, never swapped.", "属于姿势组，从不参与替换。"),
        ("Not playable here: {0}", "此处无法播放：{0}"),
        ("state {0}, channel {1}, body {2}", "状态 {0}，通道 {1}，骨架 {2}"),
        ("The condition check was skipped.", "已跳过状态检查。"),
        ("Pool of {0}: {1} usable, {2} refused. {3} of your {4} owned emotes were excluded.", "情感动作池共 {0} 个：{1} 个可用，{2} 个被拒绝。你拥有的 {4} 个情感动作中有 {3} 个被排除。"),
        ("Borrows your idle pose first. The match below is only used if that fails.", "优先借用你的待机动作，只有失败时才使用下面的匹配结果。"),
        ("No owned loop fitted. This is the lenient pass, where a one-shot can be used for a loop.", "没有合适的已拥有循环情感动作，当前为宽松匹配，可用一次性动作充当循环。"),
        ("Nothing passes the filters, so this emote cannot be bypassed here.", "没有候选能通过筛选，此处无法无视限制播放该情感动作。"),
        ("No posture variant shared with {0}. The swap stops before it is built.", "与 {0} 没有共用的姿势变体，替换在构建前中止。"),
        ("If this was to alternate, it would land on a second same-tier emote.", "若要交替播放，会落到同档的第二个情感动作。"),
        ("kept out", "已排除"),
        ("refused", "已拒绝"),
        ("chosen", "已选中"),
        ("same tier", "同档"),
        ("usable", "可用"),
        (", blocked by your rules", "，被你的规则阻止"),
        (", another of your mods changes it", "，你的另一个模组改动了它"),
        (", blocked on {0}", "，因 {0} 被阻止"),
        ("cancels on rotate", "转身即取消"),
        ("pose family", "姿势组"),
        ("never a target", "永不作为目标"),
        ("blocked by your rules", "被你的规则阻止"),
        ("intro + loop", "前奏 + 循环"),
        ("intro + one shot", "前奏 + 一次性"),
        ("loop only", "仅循环"),
        ("one shot", "一次性"),
        ("no sound", "无音效"),
        ("sound", "音效"),
        ("voiceline", "语音"),
        ("sound unknown", "音效未知"),
        ("no turn", "不转向"),
        ("eyes turn", "视线转向"),
        ("head turn", "头部转向"),
        ("body turn", "身体转向"),
        ("turn unknown", "转向未知"),
        ("no posture", "无姿势"),
        ("standing", "站立"),
        ("chair", "椅子"),
        ("ground", "地面"),
        ("mounted", "骑乘"),
        ("Unknown ({0})", "未知（{0}）"),
    ];
}
