using Dalamud.Interface;
using NoireLib.Changelog;
using System.Collections.Generic;

namespace BypassEmote.Changelog.Versions;

public class V2_3_x_x : BaseChangelogVersion
{
    public override List<ChangelogVersion> GetVersions() => new()
    {
        CreateV2_3_0_0(),
        CreateV2_3_1_0(),
    };

    private static ChangelogVersion CreateV2_3_0_0()
        => new ChangelogVersion
        {
            Version = new(2, 3, 0, 0),
            Date = "09-09-2026",
            Title = L.T("Animation refresh rework"),
            TitleColor = Blue,
            Description = L.T("Reworks how animations are refreshed, and stops other players from seeing you redraw."),
            Entries = new List<ChangelogEntry>
            {
                Header(L.T("New Features"), Orange, 0, FontAwesomeIcon.Book),
                EntryBullet(L.T("Added \"Add an override...\" to the right click menu of the main UI.\n" +
                    "It opens the \"Emote overrides\" tab with the emote already picked."), Orange, 1),
                Separator(),
                Header(L.T("Bug fixes"), LightRed, 0, FontAwesomeIcon.Bug),
                EntryBullet(L.T("\"Always cache-break\" no longer makes other players see you redraw for random emotes."), White, 1),
                Separator(),
                Header(L.T("Technical Changes"), Blue, 0, FontAwesomeIcon.Wrench),
                EntryBullet(L.T("Reworked how the plugin refreshes an animation, it is now way more efficient and optimized. Dropped from 10+ sigs to 2."), Blue, 1),
                EntryBullet(L.T("Various technical enhancements."), White, 1),
            }
        };

    private static ChangelogVersion CreateV2_3_1_0()
        => new ChangelogVersion
        {
            Version = new(2, 3, 1, 0),
            Date = "12-09-2026",
            Title = L.T("Idle pose fixes"),
            TitleColor = Blue,
            Description = L.T("Fixes loop emotes playing your own idle mod instead of the emote you asked for."),
            Entries = new List<ChangelogEntry>
            {
                Header(L.T("Bug fixes"), LightRed, 0, FontAwesomeIcon.Bug),
                EntryBullet(L.T("Loop emotes no longer play your own idle mod instead of the emote you asked for.\n" +
                    "Generated bypass mods priority was not correctly set, this is fixed now."), White, 1),
                EntryBullet(L.T("Fixed a bug where stopping a bypass on an idle animation by moving would not correctly stop the animation."), White, 1),
                EntryBullet(L.T("Fixed a bug with \"Only when nothing else fits\" for \"Loops on idle poses\" where it ignored blocked emotes."), White, 1),
                EntryBullet(L.T("/belogs now exports everything the plugin did since it loaded.\n" +
                    "It would only partially export logs when the dalamud log level was not properly set."), White, 1),
                Separator(),
                Header(L.T("Technical Changes"), Blue, 0, FontAwesomeIcon.Wrench),
                EntryBullet(L.T("The plugin reads its mod's priority back from Penumbra instead of taking the cached value."), Blue, 1),
                EntryBullet(L.T("Various technical enhancements."), White, 1),
            }
        };
}